### ISSUE TITLE
为何我引入主题,不生成search页面呢. search的时候直接get请求失败

### ISSUE THREAD

**Issue by Anthony-Dong** [qyxtim/bitcron-pro#10]
如何添加搜索功能哇

**Comment by yuxqiu** [comment]
我这里本地测试正常，能否提供一下错误截图

**Comment by Anthony-Dong** [comment]
![](https://tyut.oss-accelerate.aliyuncs.com/image/2020-40-44/48e98d17-06c8-47d4-9d9d-3868555b0189.png)
本地其实是没有生成对于的search文件的. 
![]( https://tyut.oss-accelerate.aliyuncs.com/image/2020-40-44/baf85c64-478c-475a-bcca-8cf7f6c17f85.png)
基本情况就是这些.  我的个人邮箱 574986060@qq.com , 我一直不懂这个gridea如何生成页面的. 但是确实没有生成search页面 . 客户端版本是0.83

**Comment by yuxqiu** [comment]
问题解决 #11
