### ISSUE TITLE
社交里面的元素，只有邮箱和github设置了会显示

### ISSUE THREAD

**Issue by DereenMec** [qyxtim/bitcron-pro#13]
其他的设置了，底部还是没有图标- -
{"Santa":false,"Spring":false,"envelope":"mailto:dereenmec@outlook.com","ga":"","github":"https://github.com/dereenmec","rss":"","send-o":"https://t.me/chopaa","twitter":"https://twitter.com/dereen_","weibo":"https://weibo.com/xbzzhc"}
这里是我查看的theme.bitcron-pro.config.json 文件里的内容🙃

**Comment by yuxqiu** [comment]
> 其他的设置了，底部还是没有图标- -
> {"Santa":false,"Spring":false,"envelope":"mailto:[dereenmec@outlook.com](mailto:dereenmec@outlook.com)","ga":"","github":"[https://github.com/dereenmec","rss":"","send-o":"https://t.me/chopaa","twitter":"https://twitter.com/dereen_","weibo":"https://weibo.com/xbzzhc"}](https://github.com/dereenmec%22,%22rss%22:%22%22,%22send-o%22:%22https://t.me/chopaa%22,%22twitter%22:%22https://twitter.com/dereen_%22,%22weibo%22:%22https://weibo.com/xbzzhc%22%7D)
> 这里是我查看的theme.bitcron-pro.config.json 文件里的内容🙃

这个问题今天会修复

**Comment by yuxqiu** [comment]
现已修复！

**Comment by DereenMec** [comment]
> 现已修复！

阿里嘎多！
