### ISSUE TITLE
关于代码高亮

### ISSUE THREAD

**Issue by Gunpowder-pixel** [qyxtim/bitcron-pro#15]
### 大佬，请问一下这个主题能不能自己改变代码高亮的样式

有看到教程说直接把`Prism.js`和`Prism.css`文件直接丢进Gridea的static文件夹就行了，但我试了试好像不行
所以请问大佬这个主题是怎么改变代码高亮的样式？

**Comment by yuxqiu** [comment]
如果要替换 css
1. 下载最新版本的主题
2. 打开`bitcron-pro/assets/styles/components`中的`highlight.less`
3. 用 prism.js 官网上下载下来的 css 来替换掉 less 里面的内容

如果要替换 js
1. 打开`bitcron-pro/assets/media/js`中的`prism.js`
2. 用 prism.js 官网上下载下来的 js 来替换该文件

**Comment by Gunpowder-pixel** [comment]
> 如果要替换css
> 
> 1. 下载最新版本的主题
> 2. ：`bitcron-pro/assets/styles/components`中的`highlight.less`
> 3. 用Prism.js官网上下载下来的css来替换掉less里面的内容
> 
> 如果要替换js
> 
> 1. ：`bitcron-pro/assets/media/js`中的`prism.js`
> 2. 用Prism.js官网上下载下来的js来替换该文件

大佬，我下载了最新版本的主题，也替换了`bitcron-pro/assets/styles/components`中的`highlight.less`和`bitcron-pro/assets/media/js`中的`prism.js`

js正常同步了，但是css，准确来说，`styles`文件夹里的`components`文件夹都没有同步到Github

手动上传`components`到Github的`styles`文件夹下，Gridea也会在同步的时候只剩下`main.css`

也试过把主题移出来，再重启Gridea，重新同步

或者换成别的主题同步后再切回bitcron-pro同步，依然无用

始终不能把`components`文件夹及里面的文件同步到Github上

**Comment by yuxqiu** [comment]
> 大佬，我下载了最新版本的主题，也替换了`bitcron-pro/assets/styles/components`中的`highlight.less`和`bitcron-pro/assets/media/js`中的`prism.js`
> 
> js正常同步了，但是css，准确来说，`styles`文件夹里的`components`文件夹都没有同步到Github
> 
> 手动上传`components`到Github的`styles`文件夹下，Gridea也会在同步的时候只剩下`main.css`
> 
> 也试过把主题移出来，再重启Gridea，重新同步
> 
> 或者换成别的主题同步后再切回bitcron-pro同步，依然无用
> 
> 始终不能把`components`文件夹及里面的文件同步到Github上

`components` 里面的内容是不会同步上去的，但文件夹里面`less`文件的内容会被引入到 `main.css` 里面；如果现在代码高亮的样式已经改变了，那就是 OK 了

**Comment by Gunpowder-pixel** [comment]
> > 大佬，我下载了最新版本的主题，也替换了`bitcron-pro/assets/styles/components`中的`highlight.less`和`bitcron-pro/assets/media/js`中的`prism.js`
> > js正常同步了，但是css，准确来说，`styles`文件夹里的`components`文件夹都没有同步到Github
> > 手动上传`components`到Github的`styles`文件夹下，Gridea也会在同步的时候只剩下`main.css`
> > 也试过把主题移出来，再重启Gridea，重新同步
> > 或者换成别的主题同步后再切回bitcron-pro同步，依然无用
> > 始终不能把`components`文件夹及里面的文件同步到Github上
> 
> `components`里面的内容是不会同步上去的，但文件夹里面`less`文件的内容会被`main.css`约会到里面；如果现在代码高亮的样式已经改变了，那就是OK了

emmmmm
试了好多遍，还是没有改变，心累，不折腾了
多谢大佬
