### ISSUE TITLE
嵌套引用是什么鬼？~

### ISSUE THREAD

**Issue by pwntester1337** [qyxtim/bitcron-pro#19]
![image](https://user-images.githubusercontent.com/68268423/87905884-1b499880-ca94-11ea-928c-3a02dc33a5ab.png)
这个引用怎么是这个样子的？

**Comment by yuxqiu** [comment]
你的md文件是怎么写的？

**Comment by pwntester1337** [comment]
我没改动任何东西呀~

**Comment by evilcos-blog** [comment]
里面没有md文件

**Comment by evilcos-blog** [comment]
> 引用内容
> > 使用嵌套的引用

**Comment by pwntester1337** [comment]
![image](https://user-images.githubusercontent.com/68268423/88009952-52788200-cb46-11ea-969d-59285efa9f41.png)

**Comment by yuxqiu** [comment]
这是由于Gridea渲染导致的，与主题无关
