### ISSUE TITLE
请问toc应该如何改在页面旁边？

### ISSUE THREAD

**Issue by moonaileen** [qyxtim/bitcron-pro#3]
您好，正在使用您改造的这款主题，小白一枚，想请教一下应该怎么修改main.less的toc部分才能让它不保持在页面右上角而是固定在post部分的旁边？
效果类似于这个：https://github.com/getgridea/gridea-theme-pinghsu
不知道表达是否清楚，还请赐教m(_ _)m
（尝试照搬了一下代码发现不起作用，小白请不要介意T__T）

**Comment by yuxqiu** [comment]
.toc-container{position:fixed;top:32px;width:200px;right:32px;font-size:12px;}
调整top的大小，调整到想要固定的位置即可！

**Comment by moonaileen** [comment]
那个，感谢回复。但是我发现按照这样调整后，遇到不一样分辨率显示出来的相对位置也不一样呀😭
应该怎么改让它可以随着文章部分滚动呢？
