### ISSUE TITLE
考虑支持Valine吗

### ISSUE THREAD

**Issue by ghost** [qyxtim/bitcron-pro#4]
类似云中君[pan主题](https://github.com/alterfang/gridea-theme-pan)

**Comment by ghost** [comment]
[Valine改款](https://deserts.io/diy-a-comment-system/)

**Comment by ghost** [comment]
昨天我尝试过自行添加代码，最终还是没有成功。是否考虑做成pan那样，放到主题自定义里去

**Comment by yuxqiu** [comment]
目前没有这个打算

**Comment by haoranxz** [comment]
> 昨天我尝试过自行添加代码，最终还是没有成功。是否考虑做成pan那样，放到主题自定义里去

可以成功的，参见http://blog.hrxz.net
