### ISSUE TITLE
文章摘要和字数统计是怎么设置的呢？

### ISSUE THREAD

**Issue by Macin20** [qyxtim/bitcron-pro#7]
![image](https://user-images.githubusercontent.com/46590585/69772229-5415c400-11ca-11ea-9c34-6f8a1e5313cd.png)
请教一下，
这里的摘要是如何设置的呀？我用这个主题发布的文章之后标题下面显示的 ”Read More >>>”，而且没有字数的统计哇

**Comment by yuxqiu** [comment]
在新版已经修复！
